<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>False</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Images\AppInfo.png" />
    <None Remove="Resources\Images\GreenPlus.png" />
    <None Remove="Resources\Images\MenuIcon.png" />
    <None Remove="Resources\Images\QuestionPromo.png" />
    <None Remove="Resources\Images\SettingsIcon.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinFormsHelper\WinFormsHelper.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\AppInfo.png" />
    <Resource Include="Resources\Images\GreenPlus.png" />
    <Resource Include="Resources\Images\MenuIcon.png" />
    <Resource Include="Resources\Images\QuestionPromo.png" />
    <Resource Include="Resources\Images\SettingsIcon.png" />
  </ItemGroup>

</Project>
