<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>False</UseWindowsForms>
    <SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
    <ApplicationIcon>Resources\Icons\TaskManager.ico</ApplicationIcon>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Images\DarkAppInfo.png" />
    <None Remove="Resources\Images\DarkMenuIcon.png" />
    <None Remove="Resources\Images\DarkPlus.png" />
    <None Remove="Resources\Images\DarkSettingsIcon.png" />
    <None Remove="Resources\Images\LightQuestionPromo.png" />
    <None Remove="Resources\Images\QuestionPromo.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Icons\TaskManager.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="10.0.6">
      <GeneratePathProperty></GeneratePathProperty>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinFormsHelper\WinFormsHelper.csproj">
      <Private>True</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Планировщик задач – Справка.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Resource Include="Resources\Images\LightAppInfo.png" />
    <Resource Include="Resources\Images\DarkAppInfo.png" />
    <Resource Include="Resources\Images\DarkMenuIcon.png" />
    <Resource Include="Resources\Images\DarkPlus.png" />
    <Resource Include="Resources\Images\DarkSettingsIcon.png" />
    <Resource Include="Resources\Images\LightPlus.png" />
    <Resource Include="Resources\Images\LightMenuIcon.png" />
    <Resource Include="Resources\Images\LightQuestionPromo.png" />
    <Resource Include="Resources\Images\QuestionPromo.png" />
    <Resource Include="Resources\Images\LightSettingsIcon.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Resources\Texts.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Texts.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Texts.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Texts.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
